const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const zlib = require('node:zlib');

const {
  auditPngBuffer,
  auditProjectImages,
  auditRegistry,
  compareConceptImageFiles,
  formatAuditReport,
  isCanonicalVocabularyPath,
} = require('../scripts/lib/audit-vocab-images.cjs');

const PNG_SIGNATURE = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]);

function crc32(buffer) {
  let crc = 0xffffffff;
  for (const value of buffer) {
    crc ^= value;
    for (let bit = 0; bit < 8; bit += 1) {
      crc = (crc >>> 1) ^ (0xedb88320 & -(crc & 1));
    }
  }
  return (crc ^ 0xffffffff) >>> 0;
}

function chunk(type, data) {
  const typeBuffer = Buffer.from(type, 'ascii');
  const result = Buffer.alloc(12 + data.length);
  result.writeUInt32BE(data.length, 0);
  typeBuffer.copy(result, 4);
  data.copy(result, 8);
  result.writeUInt32BE(crc32(Buffer.concat([typeBuffer, data])), 8 + data.length);
  return result;
}

function makeRgbaPng(width, height, pixelAt, textMetadata = null) {
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8;
  ihdr[9] = 6;
  const rows = [];
  for (let y = 0; y < height; y += 1) {
    const row = Buffer.alloc(1 + width * 4);
    for (let x = 0; x < width; x += 1) {
      const [r, g, b, a] = pixelAt(x, y);
      row.set([r, g, b, a], 1 + x * 4);
    }
    rows.push(row);
  }
  const chunks = [chunk('IHDR', ihdr)];
  if (textMetadata) chunks.push(chunk('tEXt', Buffer.from(textMetadata, 'latin1')));
  chunks.push(chunk('IDAT', zlib.deflateSync(Buffer.concat(rows))), chunk('IEND', Buffer.alloc(0)));
  return Buffer.concat([PNG_SIGNATURE, ...chunks]);
}

function cleanCutoutPixel(x, y) {
  const onEdge = x === 2 || x === 5 || y === 2 || y === 5;
  const inside = x >= 2 && x <= 5 && y >= 2 && y <= 5;
  if (!inside) return [0, 0, 0, 0];
  return onEdge ? [50, 110, 180, 128] : [50, 110, 180, 255];
}

test('accepts a square 8-bit RGBA cutout with real transparency and antialiased alpha', () => {
  const result = auditPngBuffer(makeRgbaPng(8, 8, cleanCutoutPixel), {
    label: 'clean.png',
    expectedWidth: 8,
    expectedHeight: 8,
  });

  assert.deepEqual(result.failures, []);
  assert.equal(result.stats.transparentPixels > 0, true);
  assert.equal(result.stats.partialAlphaPixels > 0, true);
  assert.equal(result.stats.opaquePixels > 0, true);
});

test('rejects wrong dimensions and an opaque rectangular background', () => {
  const result = auditPngBuffer(makeRgbaPng(7, 8, () => [250, 250, 250, 255]), {
    label: 'opaque.png',
    expectedWidth: 8,
    expectedHeight: 8,
  });

  assert.match(result.failures.map((failure) => failure.code).join('\n'), /INVALID_DIMENSIONS/);
  assert.match(result.failures.map((failure) => failure.code).join('\n'), /NO_TRANSPARENCY/);
  assert.match(result.failures.map((failure) => failure.code).join('\n'), /OPAQUE_BACKGROUND/);
});

test('rejects magenta chroma-key pixels at the transparency boundary', () => {
  const png = makeRgbaPng(8, 8, (x, y) => {
    if (x === 2 && y >= 2 && y <= 5) return [245, 10, 230, 255];
    return cleanCutoutPixel(x, y);
  });
  const result = auditPngBuffer(png, { label: 'halo.png', expectedWidth: 8, expectedHeight: 8 });

  const halo = result.failures.find((failure) => failure.code === 'CHROMA_KEY_HALO');
  assert.ok(halo);
  assert.equal(halo.details.pixelCount > 0, true);
});

test('rejects green chroma-key pixels at the transparency boundary', () => {
  const png = makeRgbaPng(8, 8, (x, y) => {
    if (x === 2 && y >= 2 && y <= 5) return [12, 246, 16, 220];
    return cleanCutoutPixel(x, y);
  });
  const result = auditPngBuffer(png, { label: 'green-halo.png', expectedWidth: 8, expectedHeight: 8 });

  assert.ok(result.failures.find((failure) => failure.code === 'CHROMA_KEY_HALO'));
});

test('rejects dark purple chroma contamination at a transparent hair edge', () => {
  const png = makeRgbaPng(8, 8, (x, y) => {
    if (x === 2 && y >= 2 && y <= 5) return [110, 20, 100, 180];
    return cleanCutoutPixel(x, y);
  });
  const result = auditPngBuffer(png, { label: 'purple-hair-halo.png', expectedWidth: 8, expectedHeight: 8 });

  assert.match(result.failures.map((failure) => failure.code).join('\n'), /CHROMA_KEY_HALO/);
});

test('allows legitimate pink clothing at a transparent subject edge', () => {
  const png = makeRgbaPng(8, 8, (x, y) => {
    if (x === 2 && y >= 2 && y <= 5) return [235, 30, 145, 180];
    return cleanCutoutPixel(x, y);
  });
  const result = auditPngBuffer(png, { label: 'pink-clothing.png', expectedWidth: 8, expectedHeight: 8 });

  assert.equal(result.failures.some((failure) => failure.code === 'CHROMA_KEY_HALO'), false);
});

test('rejects suspicious watermark or generation metadata', () => {
  const png = makeRgbaPng(8, 8, cleanCutoutPixel, 'Comment\0Generated by Watermark Studio');
  const result = auditPngBuffer(png, { label: 'metadata.png', expectedWidth: 8, expectedHeight: 8 });

  assert.match(result.failures.map((failure) => failure.code).join('\n'), /SUSPICIOUS_METADATA/);
});

test('allows canonical future-course references while rejecting legacy category paths', () => {
  const courseIds = ['jamaican-patois', 'swahili'];
  const conceptIds = ['yes', 'no'];

  assert.equal(isCanonicalVocabularyPath('assets/images/vocab/swahili/yes.png', courseIds, conceptIds), true);
  assert.equal(isCanonicalVocabularyPath('assets/images/vocab/family/father.png', courseIds, conceptIds), false);
  assert.equal(isCanonicalVocabularyPath('assets/images/vocab/swahili/unknown.png', courseIds, conceptIds), false);
});

test('enumerates missing, extra, and wrongly named concept PNGs', () => {
  const failures = compareConceptImageFiles(['yes', 'no'], ['yes.png', 'legacy.png'], 'assets/images/vocab/jamaican-patois');
  const codes = failures.map((failure) => failure.code);

  assert.deepEqual(codes, ['MISSING_CONCEPT_IMAGE', 'UNEXPECTED_CONCEPT_IMAGE']);
  assert.match(failures[0].message, /no/);
  assert.match(failures[1].target, /legacy\.png/);
});

test('registry audit rejects missing, extra, and misdirected static requires', (context) => {
  const projectRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'diaspora-image-registry-'));
  context.after(() => fs.rmSync(projectRoot, { recursive: true, force: true }));
  const registryPath = path.join(projectRoot, 'src', 'data', 'jamaicanPatoisImageRegistry.js');
  fs.mkdirSync(path.dirname(registryPath), { recursive: true });
  fs.writeFileSync(registryPath, [
    'export const REGISTRY = {',
    "  'yes': require('../../assets/images/vocab/family/yes.png'),",
    "  'legacy': require('../../assets/images/vocab/family/legacy.png'),",
    '};',
  ].join('\n'));
  const expectedPaths = new Map([
    ['yes', 'assets/images/vocab/jamaican-patois/yes.png'],
    ['no', 'assets/images/vocab/jamaican-patois/no.png'],
  ]);

  const codes = new Set(auditRegistry(projectRoot, ['yes', 'no'], expectedPaths).map((failure) => failure.code));
  assert.equal(codes.has('REGISTRY_COUNT_MISMATCH'), false);
  assert.equal(codes.has('INVALID_REGISTRY_PATH'), true);
  assert.equal(codes.has('MISSING_REGISTRY_ENTRY'), true);
  assert.equal(codes.has('UNEXPECTED_REGISTRY_ENTRY'), true);
});

test('current Patois asset tree contains only the approved canonical cutouts and chapter hero', () => {
  const projectRoot = path.resolve(__dirname, '..');
  const result = auditProjectImages(projectRoot);

  assert.equal(result.ok, true, formatAuditReport(result));
  assert.equal(result.summary.expectedConceptCount, 39);
  assert.equal(result.summary.vocabPngCount, 39);
  assert.equal(result.summary.auditedPngCount, 39);
  assert.deepEqual(result.failures, []);

  const report = formatAuditReport(result);
  assert.match(report, /PASSED/);
  assert.match(report, /Failures: 0/);
});
