const VOICE_ROLES = Object.freeze({
  'narrator-en': Object.freeze({
    roleKind: 'interface-narrator',
    character: null,
    locale: 'en',
    purpose: 'base-language-instruction',
    voiceEnvVar: 'ELEVENLABS_VOICE_ID_NARRATOR_ENGLISH',
    displayName: 'Neutral English instructional narrator — unassigned',
    enabled: false,
    status: 'voice-audition-required',
  }),
  'narrator-fr': Object.freeze({
    roleKind: 'interface-narrator',
    character: null,
    locale: 'fr',
    purpose: 'base-language-instruction',
    voiceEnvVar: 'ELEVENLABS_VOICE_ID_NARRATOR_FRENCH',
    displayName: 'French instructional narrator — Stella candidate',
    enabled: false,
    status: 'voice-audition-required',
  }),
  'narrator-ar': Object.freeze({
    roleKind: 'interface-narrator',
    character: null,
    locale: 'ar',
    purpose: 'base-language-instruction',
    voiceEnvVar: 'ELEVENLABS_VOICE_ID_NARRATOR_ARABIC',
    displayName: 'Arabic instructional narrator — unassigned (not Laloosh)',
    enabled: false,
    status: 'voice-audition-required',
  }),
  'kai-denzel': Object.freeze({
    roleKind: 'character-dialogue',
    character: 'Kai',
    locale: 'en-JM',
    purpose: 'character-dialogue',
    voiceEnvVar: 'ELEVENLABS_VOICE_ID_PATOIS',
    displayName: 'Denzel - Jamaican, Raspy, and Deep',
    enabled: false,
    status: 'voice-audition-required',
  }),
  'amara-annakay': Object.freeze({
    roleKind: 'character-dialogue',
    character: 'Amara',
    locale: 'en-JM',
    purpose: 'character-dialogue',
    voiceEnvVar: 'ELEVENLABS_VOICE_ID_JAMAICAN',
    displayName: 'Annakay - Jamaican, Bright, Young, Storytelling, Narrator',
    enabled: false,
    status: 'voice-audition-required',
  }),
  'target-patois-denzel': Object.freeze({
    roleKind: 'target-language',
    character: null,
    locale: 'en-JM',
    purpose: 'core-vocabulary',
    voiceEnvVar: 'ELEVENLABS_VOICE_ID_PATOIS',
    displayName: 'Denzel - Jamaican, Raspy, and Deep',
    enabled: false,
    status: 'voice-audition-required',
  }),
  'target-patois-annakay': Object.freeze({
    roleKind: 'target-language',
    character: null,
    locale: 'en-JM',
    purpose: 'core-vocabulary',
    voiceEnvVar: 'ELEVENLABS_VOICE_ID_JAMAICAN',
    displayName: 'Annakay - Jamaican, Bright, Young, Storytelling, Narrator',
    enabled: false,
    status: 'voice-audition-required',
  }),
  'sol-silent': Object.freeze({
    roleKind: 'silent-character',
    character: 'Sol',
    locale: null,
    purpose: 'character-dialogue',
    voiceEnvVar: null,
    displayName: 'Sol — intentionally silent',
    enabled: false,
    status: 'intentionally-silent-until-approved',
  }),
});

module.exports = { VOICE_ROLES };
